#[cfg(not(target_arch = "wasm32"))]
pub mod cli;
#[cfg(not(target_arch = "wasm32"))]
pub mod config;
pub mod detector;
#[cfg(not(target_arch = "wasm32"))]
pub mod diff;
pub mod engine;
#[cfg(not(target_arch = "wasm32"))]
pub mod interactive;
#[cfg(not(target_arch = "wasm32"))]
pub mod lsp;
#[cfg(not(target_arch = "wasm32"))]
pub mod report;
pub mod rules;
#[cfg(not(target_arch = "wasm32"))]
pub mod scanner;
#[cfg(not(target_arch = "wasm32"))]
pub mod watch;
